### ISSUE TITLE
Is it possible to send spans themselves with http?

### ISSUE THREAD

**Issue by seenudus** [jaegertracing/jaeger-client-node#171] opened 2017-11-08 14:13 UTC
I have a case where some parts of the code are executed in an isolated 1-way traffic environment. Meaning there is no jaeger stack available, other than the client libraries. So the spans created there don't end up in the jaeger collector where the first call was made.

Is it possible to send span data, together with context? Then in the initial service which made the external call, we can send spans to remote reporter.

**Comment by black-adder** [comment] 2017-11-08 15:32
Closing as a duplicate of https://github.com/jaegertracing/jaeger-client-node/issues/170

Feel free to open again if you feel like the tickets address different concerns.

**Comment by yurishkuro** [comment] 2017-11-08 16:18
I don't think this is a duplicate, the question is about sending span data in-band

**Comment by seenudus** [comment] 2017-11-09 09:29
Yes, @yurishkuro is correct, sending span data in-band is what I'm asking. Is it possible, and if not, is it planned to be supported? It would remove the necessity of having agent and collector available during the whole request lifecycle. I'm pretty sure there are many more cases where some requests end up in isolated networks which are allowed to respond to connections, not invoke them (to jaeger agent & collector).

It would offer a big advantage, because you could then start tracing over many different networks.

This is sadly one of the reasons we are also considering new relic opentracing solution. It costs a lot and is not as simple and elegant as jaeger, but it removes the network infrastructure problem from our end.

**Comment by yurishkuro** [comment] 2017-11-09 22:20
Sending spans in-band is not implemented in any of Jaeger clients, we haven't even considered that as an option tbh, although it's not impossible to implement, in theory. But it means we'd be using the business channel for monitoring data, many apps won't like that. Also, typically the root span will only be finished once the frontend receives the response from the backend, so that span can only be reported in the _next_ request, which means we're using business change as async. At that point why not just use a completely independent async request?  Yes, your edge proxy would need to pass through the spans to the collectors.

I'd be interested to hear your thoughts on how to make Jaeger easier to use in this regard. Are you saying NewRelic reports monitoring data in-band with business traffic?

**Comment by yurishkuro** [comment] 2018-02-20 05:11
closing due to inactivity

**Closed by yurishkuro** 2018-02-20 05:11 UTC
