### ISSUE TITLE
Module not found: Error: Can't resolve 'hexer'

### ISSUE THREAD

**Issue by andrew-kirkham** [jaegertracing/jaeger-client-node#368] opened 2019-05-31 15:49 UTC
## Requirement - what kind of business use case are you trying to solve?

Trying to build our Node application with jaeger-client installed. Our CI project uses webpack.

## Problem - what in Jaeger blocks you from solving the requirement?

On build we see
```
Module not found: Error: Can't resolve 'hexer' in '.../node_modules/bufrw'
     @ .../node_modules/bufrw/annotated_buffer.js 27:10-26
     @ .../node_modules/bufrw/interface.js
     @ .../node_modules/bufrw/index.js
     @ .../node_modules/thriftrw/index.js
     @ .../node_modules/jaeger-client/dist/src/reporters/http_sender.js
     @ .../node_modules/jaeger-client/dist/src/configuration.js
     @ .../node_modules/jaeger-client/dist/src/index.js
     @ .../src/server.js
```

This prevents us from building our project with the jaeger-client. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Are there any other libraries that can be used in place? The underlying `bufrw` project seems to have fixed the requirement but never pushed up the fix to npm registry and the project no longer appears to be maintained. 
Related issue: https://github.com/uber/bufrw/issues/65.

**Comment by grzegorzjudas** [comment] 2019-06-01 14:31
Worth noting this happens most likely when bundling the code using webpack - as it tried to pre-load all packages on build time and doesn't care for if or try/catch statements that are present in this case.

I tried adding jeager-client-node on both non-webpack and webpack project and the non-webpack one worked just fine.

**Comment by Bessonov** [comment] 2019-08-02 16:51
Not sure why `bufrw` needed.

Adding hexer as dependency helps to build the project with webpack, but fails on runtime with:
```
Error: ENOENT: no such file or directory, open '/jaeger-idl/thrift/jaeger.thrift'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
[...]
```

in this place:

```
ThriftUtils._thrift = new _thriftrw.Thrift({
  source: _fs2.default.readFileSync(
    _path2.default.join(__dirname, './jaeger-idl/thrift/jaeger.thrift'),
    'ascii'
  ),
  allowOptionalArguments: true,
});
ThriftUtils.emptyBuffer = new Buffer([0, 0, 0, 0, 0, 0, 0, 0]);
exports.default = ThriftUtils;
```

`__dirname` was set to `/`. Fixed with:

```
	node: {
		__dirname: false,
		__filename: false,
	},
```

And then copied files to expected (and different - why?) locations. But ran into:

```
assert.js:339
    throw err;
    ^

AssertionError [ERR_ASSERTION]: every field must be marked optional, required, or have a default value on Endpoint including "ipv4" in strict mode
```
Not sure how to use the client at all.

**Comment by yurishkuro** [comment] 2019-08-23 18:10
Can someone please provide a reproducible example?

**Comment by jamietre** [comment] 2020-02-12 16:53
I'm also trying to use this with webpack bundling. The problem is that `jaeger-node-client` loads files from the `jaeger-idl` subrepo at runtime using `fs.readFileSync`, but this doesn't make sense in the context of a webpack bundle. Webpack is "smart" enough to bundle up assets loaded at runtime with `require`, if it can determine the target at build time, but `fs` is *always* an external with the "node" webpack target.

I've gotten it to work successfully using quite a bit of hacking on webpack -

- generate javascript file that returns same info as in `jaeger-idl` repo so it can be consumed as a normal static dependency
- create custom webpack target that excludes `fs` from externals
- implement fake `fs.readFileSync` that maps the path to the correct export on generated file from first step

It works fine with these changes. 

It would be a lot easier if the `jaeger-node-client` just included the thrift data models as regular static dependencies instead of loading them at runtime; they aren't especially big. If there's no special reason not to do this, would you be open to a pull request that removes the `fs.readFileSync` dependency making this easily webpackable?

**Comment by yurishkuro** [comment] 2020-02-12 18:43
@jamietre I think it's reasonable to convert IDL files into js files that directly embed the schemas. We already copy them as part of the build: https://github.com/jaegertracing/jaeger-client-node/blob/18a2d3479ff8a05b2cd853d3ca139c28bb224159/Makefile#L66

**Comment by jamietre** [comment] 2020-02-12 18:51
@yurishkuro cool, I'll clean this up and make a PR.

**Closed** 2022-01-10 19:24 UTC
