### ISSUE TITLE
Memory leak in UDPSender

### ISSUE THREAD

**Issue by aviranco** [jaegertracing/jaeger-client-node#208] opened 2018-01-23 16:21 UTC
I am currently investigating a memory leak, the application memory consumption is consistently when I use jaeger to write logs and the application crashes due to that leak after a period of time.

Note that If I disable the jaeger logs there is no memory leak - its how I know its something related to jaeger

To narrow down the possibilities I've removed all the logs writing in jaeger, and only kept the span creation and calling to "span.finish()" and the leaks still persists.

I've also verified that for every span I create I call span.finish(), so it appears that my applicative code does not create the leak.

I've made heap memory snapshots few seconds after the start, and snapshots after jaeger usage. when I analyze the heap memory difference between the snapshots, the highest growth in "retained size" addresses the **RemoteReporter** and **UDPSender** constructor. I've played with the jaeger code, but could not find the exact place that leaks, but it seems its something to do with the remote reporter.
 
![screen shot 2018-01-23 at 18 15 16](https://user-images.githubusercontent.com/1299681/35286773-90c0efa2-0069-11e8-8616-309fd0045354.png)

This is the configuration I use:
```
{
      reporter: {
        flushIntervalMs: 1000,
        agentHost: loggingServerHost,
        agentPort: 6832
      },
      sampler: {
        type: 'const',
        param: 1,
        host: loggingServerHost,
        port: 5778,
        refreshIntervalMs: 5000
      }
    }
```

Are you aware/experienced memory leaks, or its working in production without consuming more and more memory over time? If not, I am not sure what can cause such an issue, since the logs are written as expected.

Thanks

**Comment by yurishkuro** [comment] 2018-01-23 16:28
How frequently does your application generate the spans? In other languages jaeger clients utilize a fixed size queue of spans, which once filled starts dropping spans, indicating that client is not able so send spans out of process fast enough. But Node client does not employ such buffer iirc (we should add one).

**Comment by aviranco** [comment] 2018-01-24 01:09
I believe the application generates 10's spans per second but can easily can create 100's per second. Is that an issue in node client? I really wonder what should I do to avoid/fix this leak since its causing our app to crash. 

Thank for the help

**Comment by aviranco** [comment] 2018-01-24 13:50
Additionally, there is any change the #210 issue I've experienced is somehow related?

**Comment by black-adder** [comment] 2018-01-24 20:16
I've tried to reproduce and failed. I'm using a similar request pattern as you suggested (100rps) and I can't get it to leak. Did this for both latest and 3.7.0.

![image](https://user-images.githubusercontent.com/791791/35354836-5b99a2dc-0119-11e8-9532-ffea481ba36d.png)

One thing I noticed is that in your heap profile, it looks like there are loads of RemoteReporters that have been generated. Are you by any chance initializing a tracer, sampler or remote reporter per request? I can't seem to recreate the same memory usage pattern.

**Comment by aviranco** [comment] 2018-01-25 20:58
@black-adder Yes I am creating new tracer (using initTracer) for every request. Is that an issue that causes memory leaks?

**Comment by black-adder** [comment] 2018-01-25 22:06
Creating a new tracer for every request is an anti pattern and should be avoided. If the tracers aren't being freed up then yes, you could potentially have memory leaks but this shouldn't be happening in the first place.

**Comment by aviranco** [comment] 2018-01-27 22:58
@black-adder Thanks, I will make sure there will be only one tracer instance per process and will check if the leak persists. However, there is any function to "free" the tracers? I couldn't find any.

**Comment by black-adder** [comment] 2018-01-28 00:11
https://github.com/jaegertracing/jaeger-client-node/blob/master/src/tracer.js#L310

**Comment by yurishkuro** [comment] 2018-02-25 20:30
closing as invalid. Please reopen if needed

**Closed by yurishkuro** 2018-02-25 20:30 UTC
Labels: invalid
